//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QteaLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QteaLib.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for JavaScript 2.0 by Svante Lidman --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;JavaScript&quot; extensions=&quot;.js&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///	&lt;Color name=&quot;Digits&quot; foreground=&quot;DarkBlue&quot; /&gt;
        ///	&lt;Color name=&quot;Comment&quot; foreground=&quot;DarkSlateGray&quot; /&gt;
        ///	&lt;Color name=&quot;String&quot; foreground=&quot;Sienna&quot; /&gt;
        ///	&lt;Color name=&quot;Character&quot; foreground=&quot;Sienna&quot; /&gt;
        ///	&lt;Color name=&quot;JavaScriptKeyWords&quot; foreg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JSHighlighting {
            get {
                return ResourceManager.GetString("JSHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for JavaScript 2.0 by Svante Lidman --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;JavaScript&quot; extensions=&quot;.js&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///	&lt;Color name=&quot;Foreground&quot; foreground=&quot;White&quot; /&gt;
        ///	&lt;Color name=&quot;Digits&quot; foreground=&quot;DarkBlue&quot; /&gt;
        ///	&lt;Color name=&quot;Comment&quot; foreground=&quot;DarkSlateGray&quot; /&gt;
        ///	&lt;Color name=&quot;String&quot; foreground=&quot;Sienna&quot; /&gt;
        ///	&lt;Color name=&quot;Character&quot; foreground=&quot;Si [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QmlHighlighting {
            get {
                return ResourceManager.GetString("QmlHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import QtQuick 1.0
        ///
        ///Item {
        ///	id: main
        ///	width: 800
        ///	height: 600
        ///}
        ///.
        /// </summary>
        public static string QmlMainTemplate {
            get {
                return ResourceManager.GetString("QmlMainTemplate", resourceCulture);
            }
        }
    }
}
